spring:
  profiles:
    active: db
  cache:
    type: ehcache
    ehcache:
      config: classpath:/config/ehcache.xml


logging:
  level:
    com:
      example: debug
  file:
    name: logs/provider.log
server:
  port: 12345
